// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package chimera // import "go/chimera"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// The Apiversion on which the server is running
type ApiVersion struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiVersion) Reset()         { *m = ApiVersion{} }
func (m *ApiVersion) String() string { return proto.CompactTextString(m) }
func (*ApiVersion) ProtoMessage()    {}
func (*ApiVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1d31367758d96f99, []int{0}
}
func (m *ApiVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiVersion.Unmarshal(m, b)
}
func (m *ApiVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiVersion.Marshal(b, m, deterministic)
}
func (dst *ApiVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiVersion.Merge(dst, src)
}
func (m *ApiVersion) XXX_Size() int {
	return xxx_messageInfo_ApiVersion.Size(m)
}
func (m *ApiVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ApiVersion proto.InternalMessageInfo

func (m *ApiVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// The server response from an `upcheck` request
type UpCheckResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpCheckResponse) Reset()         { *m = UpCheckResponse{} }
func (m *UpCheckResponse) String() string { return proto.CompactTextString(m) }
func (*UpCheckResponse) ProtoMessage()    {}
func (*UpCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1d31367758d96f99, []int{1}
}
func (m *UpCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpCheckResponse.Unmarshal(m, b)
}
func (m *UpCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpCheckResponse.Marshal(b, m, deterministic)
}
func (dst *UpCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpCheckResponse.Merge(dst, src)
}
func (m *UpCheckResponse) XXX_Size() int {
	return xxx_messageInfo_UpCheckResponse.Size(m)
}
func (m *UpCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpCheckResponse proto.InternalMessageInfo

func (m *UpCheckResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Store a transaction payload
type SendRequest struct {
	// The payload of the transaction to be sent
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// The key of the Sender
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// The keys of all the Receipients who are privy to the transaction
	To                   []string `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1d31367758d96f99, []int{2}
}
func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (dst *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(dst, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SendRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SendRequest) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

// Response from the server for the SendRequest
type SendResponse struct {
	// The transaction hash is returned
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1d31367758d96f99, []int{3}
}
func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (dst *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(dst, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

// Retrieve a transaction payload
type ReceiveRequest struct {
	// The transaction hash to be queried
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The Senders key
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveRequest) Reset()         { *m = ReceiveRequest{} }
func (m *ReceiveRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiveRequest) ProtoMessage()    {}
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1d31367758d96f99, []int{4}
}
func (m *ReceiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveRequest.Unmarshal(m, b)
}
func (m *ReceiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveRequest.Marshal(b, m, deterministic)
}
func (dst *ReceiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveRequest.Merge(dst, src)
}
func (m *ReceiveRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiveRequest.Size(m)
}
func (m *ReceiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveRequest proto.InternalMessageInfo

func (m *ReceiveRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ReceiveRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

// Response for ReceiveRequest -> contains the transaction payload
type ReceiveResponse struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveResponse) Reset()         { *m = ReceiveResponse{} }
func (m *ReceiveResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveResponse) ProtoMessage()    {}
func (*ReceiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1d31367758d96f99, []int{5}
}
func (m *ReceiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveResponse.Unmarshal(m, b)
}
func (m *ReceiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveResponse.Marshal(b, m, deterministic)
}
func (dst *ReceiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveResponse.Merge(dst, src)
}
func (m *ReceiveResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveResponse.Size(m)
}
func (m *ReceiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveResponse proto.InternalMessageInfo

func (m *ReceiveResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Node information
type PartyInfo struct {
	// the URL identifying this node
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// public key of the respective URL
	Recipients map[string][]byte `protobuf:"bytes,2,rep,name=recipients,proto3" json:"recipients,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// All the URLs opf the connected nodes
	Parties              map[string]bool `protobuf:"bytes,3,rep,name=parties,proto3" json:"parties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PartyInfo) Reset()         { *m = PartyInfo{} }
func (m *PartyInfo) String() string { return proto.CompactTextString(m) }
func (*PartyInfo) ProtoMessage()    {}
func (*PartyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1d31367758d96f99, []int{6}
}
func (m *PartyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyInfo.Unmarshal(m, b)
}
func (m *PartyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyInfo.Marshal(b, m, deterministic)
}
func (dst *PartyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyInfo.Merge(dst, src)
}
func (m *PartyInfo) XXX_Size() int {
	return xxx_messageInfo_PartyInfo.Size(m)
}
func (m *PartyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartyInfo proto.InternalMessageInfo

func (m *PartyInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PartyInfo) GetRecipients() map[string][]byte {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *PartyInfo) GetParties() map[string]bool {
	if m != nil {
		return m.Parties
	}
	return nil
}

// Payload consisting of the partyinfo of the connected party
type PartyInfoResponse struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartyInfoResponse) Reset()         { *m = PartyInfoResponse{} }
func (m *PartyInfoResponse) String() string { return proto.CompactTextString(m) }
func (*PartyInfoResponse) ProtoMessage()    {}
func (*PartyInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1d31367758d96f99, []int{7}
}
func (m *PartyInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyInfoResponse.Unmarshal(m, b)
}
func (m *PartyInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyInfoResponse.Marshal(b, m, deterministic)
}
func (dst *PartyInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyInfoResponse.Merge(dst, src)
}
func (m *PartyInfoResponse) XXX_Size() int {
	return xxx_messageInfo_PartyInfoResponse.Size(m)
}
func (m *PartyInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PartyInfoResponse proto.InternalMessageInfo

func (m *PartyInfoResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// The Encrypted payload used to propogate the new transaction payload to other Chimera nodes
type EncryptedPayload struct {
	Sender               []byte   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	CipherText           []byte   `protobuf:"bytes,2,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ReciepientBoxes      [][]byte `protobuf:"bytes,4,rep,name=reciepientBoxes,proto3" json:"reciepientBoxes,omitempty"`
	ReciepientNonce      []byte   `protobuf:"bytes,5,opt,name=reciepientNonce,proto3" json:"reciepientNonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedPayload) Reset()         { *m = EncryptedPayload{} }
func (m *EncryptedPayload) String() string { return proto.CompactTextString(m) }
func (*EncryptedPayload) ProtoMessage()    {}
func (*EncryptedPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1d31367758d96f99, []int{8}
}
func (m *EncryptedPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedPayload.Unmarshal(m, b)
}
func (m *EncryptedPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedPayload.Marshal(b, m, deterministic)
}
func (dst *EncryptedPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedPayload.Merge(dst, src)
}
func (m *EncryptedPayload) XXX_Size() int {
	return xxx_messageInfo_EncryptedPayload.Size(m)
}
func (m *EncryptedPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedPayload.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedPayload proto.InternalMessageInfo

func (m *EncryptedPayload) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *EncryptedPayload) GetCipherText() []byte {
	if m != nil {
		return m.CipherText
	}
	return nil
}

func (m *EncryptedPayload) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *EncryptedPayload) GetReciepientBoxes() [][]byte {
	if m != nil {
		return m.ReciepientBoxes
	}
	return nil
}

func (m *EncryptedPayload) GetReciepientNonce() []byte {
	if m != nil {
		return m.ReciepientNonce
	}
	return nil
}

// The message type to sent over to other Chimera nodes.
type PushPayload struct {
	Ep *EncryptedPayload `protobuf:"bytes,1,opt,name=ep,proto3" json:"ep,omitempty"`
	// Encoded transaction information
	Encoded              []byte   `protobuf:"bytes,2,opt,name=encoded,proto3" json:"encoded,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushPayload) Reset()         { *m = PushPayload{} }
func (m *PushPayload) String() string { return proto.CompactTextString(m) }
func (*PushPayload) ProtoMessage()    {}
func (*PushPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_messages_1d31367758d96f99, []int{9}
}
func (m *PushPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPayload.Unmarshal(m, b)
}
func (m *PushPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPayload.Marshal(b, m, deterministic)
}
func (dst *PushPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPayload.Merge(dst, src)
}
func (m *PushPayload) XXX_Size() int {
	return xxx_messageInfo_PushPayload.Size(m)
}
func (m *PushPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPayload.DiscardUnknown(m)
}

var xxx_messageInfo_PushPayload proto.InternalMessageInfo

func (m *PushPayload) GetEp() *EncryptedPayload {
	if m != nil {
		return m.Ep
	}
	return nil
}

func (m *PushPayload) GetEncoded() []byte {
	if m != nil {
		return m.Encoded
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiVersion)(nil), "protofiles.ApiVersion")
	proto.RegisterType((*UpCheckResponse)(nil), "protofiles.UpCheckResponse")
	proto.RegisterType((*SendRequest)(nil), "protofiles.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "protofiles.SendResponse")
	proto.RegisterType((*ReceiveRequest)(nil), "protofiles.ReceiveRequest")
	proto.RegisterType((*ReceiveResponse)(nil), "protofiles.ReceiveResponse")
	proto.RegisterType((*PartyInfo)(nil), "protofiles.PartyInfo")
	proto.RegisterMapType((map[string]bool)(nil), "protofiles.PartyInfo.PartiesEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "protofiles.PartyInfo.RecipientsEntry")
	proto.RegisterType((*PartyInfoResponse)(nil), "protofiles.PartyInfoResponse")
	proto.RegisterType((*EncryptedPayload)(nil), "protofiles.EncryptedPayload")
	proto.RegisterType((*PushPayload)(nil), "protofiles.PushPayload")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_messages_1d31367758d96f99) }

var fileDescriptor_messages_1d31367758d96f99 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xd1, 0x6a, 0x13, 0x41,
	0x14, 0x25, 0xbb, 0x6d, 0x35, 0x37, 0x21, 0x69, 0x17, 0x91, 0x25, 0x14, 0x09, 0x0b, 0x4a, 0xa0,
	0xba, 0x81, 0x08, 0x22, 0x45, 0x1f, 0x9a, 0x92, 0x07, 0x11, 0x24, 0x8c, 0xd6, 0x07, 0xdf, 0xa6,
	0xbb, 0x37, 0xc9, 0x90, 0xcd, 0xcc, 0x38, 0x33, 0x09, 0xdd, 0x8f, 0xf1, 0x07, 0x7c, 0xf6, 0x03,
	0x65, 0x66, 0x67, 0xd3, 0x35, 0x16, 0xf4, 0x69, 0xef, 0xbd, 0x9c, 0x7b, 0xee, 0x39, 0x67, 0x16,
	0x7a, 0x1b, 0xd4, 0x9a, 0x2e, 0x51, 0xa7, 0x52, 0x09, 0x23, 0x22, 0x70, 0x9f, 0x05, 0x2b, 0x50,
	0x0f, 0xce, 0x97, 0x42, 0x2c, 0x0b, 0x1c, 0x53, 0xc9, 0xc6, 0x94, 0x73, 0x61, 0xa8, 0x61, 0x82,
	0x7b, 0x64, 0xf2, 0x02, 0xe0, 0x4a, 0xb2, 0xaf, 0xa8, 0x34, 0x13, 0x3c, 0x8a, 0xe1, 0xd1, 0xae,
	0x2a, 0xe3, 0xd6, 0xb0, 0x35, 0x6a, 0x93, 0xba, 0x4d, 0x2e, 0xa0, 0x7f, 0x23, 0xaf, 0x57, 0x98,
	0xad, 0x09, 0x6a, 0x29, 0xb8, 0x46, 0x0b, 0xf6, 0x67, 0x6b, 0xb0, 0x6f, 0x93, 0x8f, 0xd0, 0xf9,
	0x8c, 0x3c, 0x27, 0xf8, 0x7d, 0x8b, 0xda, 0x58, 0xa0, 0xa4, 0x65, 0x21, 0x68, 0xee, 0x80, 0x5d,
	0x52, 0xb7, 0x51, 0x04, 0x47, 0x0b, 0x25, 0x36, 0x71, 0xe0, 0xf6, 0x5d, 0x1d, 0xf5, 0x20, 0x30,
	0x22, 0x0e, 0x87, 0xe1, 0xa8, 0x4d, 0x02, 0x23, 0x92, 0x21, 0x74, 0x2b, 0x32, 0x7f, 0xf6, 0x14,
	0xc2, 0x35, 0x96, 0x9e, 0xc9, 0x96, 0xc9, 0x04, 0x7a, 0x04, 0x33, 0x64, 0x3b, 0xac, 0x2f, 0xfe,
	0x85, 0xf1, 0xac, 0xd5, 0x1d, 0xcb, 0x7a, 0x01, 0xfd, 0xfd, 0xce, 0xbd, 0x9f, 0x87, 0x65, 0x26,
	0x3f, 0x02, 0x68, 0xcf, 0xa9, 0x32, 0xe5, 0x07, 0xbe, 0x10, 0x96, 0x7c, 0xab, 0x0a, 0xef, 0xd9,
	0x96, 0xd1, 0x0c, 0x40, 0x61, 0xc6, 0x24, 0x43, 0x6e, 0x74, 0x1c, 0x0c, 0xc3, 0x51, 0x67, 0xf2,
	0x3c, 0xbd, 0x7f, 0x83, 0x74, 0xbf, 0x9c, 0x92, 0x3d, 0x6e, 0xc6, 0x8d, 0x2a, 0x49, 0x63, 0x31,
	0x7a, 0x67, 0x05, 0x28, 0xc3, 0x50, 0x3b, 0xfb, 0x9d, 0x49, 0xf2, 0x30, 0xc7, 0xbc, 0x02, 0x55,
	0x04, 0xf5, 0xca, 0xe0, 0xbd, 0x73, 0xd4, 0x24, 0x6f, 0xc6, 0xd0, 0xae, 0x62, 0x78, 0x02, 0xc7,
	0x3b, 0x5a, 0x6c, 0xd1, 0x25, 0xd1, 0x25, 0x55, 0x73, 0x19, 0xbc, 0x6d, 0x0d, 0x2e, 0xa1, 0xdb,
	0xe4, 0xfd, 0xd7, 0xee, 0xe3, 0xc6, 0x6e, 0xf2, 0x0a, 0xce, 0xf6, 0xea, 0xfe, 0x23, 0xce, 0x5f,
	0x2d, 0x38, 0x9d, 0xf1, 0x4c, 0x95, 0xd2, 0x60, 0x3e, 0xf7, 0xbf, 0xc2, 0x53, 0x38, 0xd1, 0xc8,
	0x73, 0x54, 0x1e, 0xed, 0xbb, 0xe8, 0x19, 0x40, 0xc6, 0xe4, 0x0a, 0xd5, 0x17, 0xbc, 0x33, 0x5e,
	0x76, 0x63, 0x62, 0x55, 0x71, 0xc1, 0x33, 0x8c, 0xc3, 0xca, 0x91, 0x6b, 0xa2, 0x11, 0xf4, 0x6d,
	0xb0, 0xe8, 0xd2, 0x98, 0x8a, 0x3b, 0xd4, 0xf1, 0xd1, 0x30, 0x1c, 0x75, 0xc9, 0xe1, 0xf8, 0x4f,
	0xe4, 0x27, 0xc7, 0x74, 0xec, 0x98, 0x0e, 0xc7, 0xc9, 0x0d, 0x74, 0xe6, 0x5b, 0xbd, 0xaa, 0x05,
	0xbf, 0x84, 0x00, 0xa5, 0x13, 0xdb, 0x99, 0x9c, 0x37, 0x1f, 0xea, 0xd0, 0x1a, 0x09, 0x50, 0xda,
	0x34, 0x90, 0x67, 0x22, 0xc7, 0xdc, 0x7b, 0xa8, 0xdb, 0xe9, 0x1b, 0x88, 0x98, 0x48, 0x6f, 0x8b,
	0x75, 0x9a, 0xad, 0xd8, 0x06, 0x15, 0x4d, 0xa9, 0x64, 0xf3, 0xd6, 0x37, 0x58, 0x8a, 0xb1, 0x9f,
	0xfc, 0x0c, 0xce, 0xa6, 0xc5, 0x9a, 0x89, 0xf4, 0xda, 0x23, 0xae, 0x24, 0xbb, 0x3d, 0x71, 0x27,
	0x5f, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xd4, 0xe6, 0x9e, 0xfc, 0x03, 0x00, 0x00,
}
