// Code generated by protoc-gen-go. DO NOT EDIT.
// source: grpc.proto

package chimera

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() { proto.RegisterFile("grpc.proto", fileDescriptor_bedfbfc9b54e5600) }

var fileDescriptor_bedfbfc9b54e5600 = []byte{
	// 381 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0xcd, 0x6e, 0xe2, 0x30,
	0x14, 0x85, 0x05, 0x82, 0x04, 0x59, 0x9a, 0x01, 0xcc, 0x8f, 0x46, 0xd1, 0xac, 0xb2, 0x9c, 0x45,
	0x22, 0x0d, 0x8c, 0x34, 0x9a, 0x1d, 0x3f, 0x1a, 0x69, 0x36, 0xa3, 0x28, 0x94, 0x2e, 0xba, 0x33,
	0xe1, 0x92, 0x58, 0x04, 0xdb, 0x8d, 0x1d, 0x2a, 0xb6, 0x7d, 0x85, 0xbe, 0x45, 0x1f, 0xa5, 0xdb,
	0xbe, 0x42, 0x1f, 0xa4, 0x72, 0x62, 0x22, 0x4a, 0x5b, 0x56, 0xd6, 0xf9, 0xae, 0xcf, 0xb9, 0x3a,
	0x17, 0xa1, 0x38, 0x13, 0x91, 0x27, 0x32, 0xae, 0x38, 0x6e, 0x16, 0x8f, 0xf3, 0x3d, 0xe6, 0x3c,
	0x4e, 0xc1, 0x27, 0x82, 0xfa, 0x84, 0x31, 0xae, 0x88, 0xa2, 0x9c, 0xc9, 0xf2, 0x93, 0xf3, 0x75,
	0x07, 0x52, 0x92, 0x18, 0x8c, 0xfe, 0xf9, 0xd4, 0x40, 0xd6, 0x2c, 0xa5, 0xc0, 0x14, 0x9e, 0x23,
	0xfb, 0x1a, 0x32, 0x49, 0x39, 0xc3, 0xdd, 0x72, 0xea, 0x4d, 0x04, 0x35, 0xc8, 0x79, 0x8f, 0xdc,
	0xde, 0xfd, 0xf3, 0xcb, 0x43, 0xfd, 0x8b, 0xdb, 0xf2, 0xf7, 0x25, 0xf9, 0x53, 0xfb, 0x81, 0xff,
	0x23, 0x7b, 0x29, 0xa2, 0x04, 0xa2, 0x2d, 0x1e, 0x1a, 0xcb, 0x52, 0xcc, 0xb4, 0x0e, 0x41, 0x0a,
	0xce, 0x24, 0x38, 0x9f, 0xf0, 0x93, 0xbc, 0xbc, 0x4c, 0xd0, 0x79, 0x3e, 0x6a, 0x2c, 0x80, 0xad,
	0x31, 0x36, 0x26, 0x2d, 0x42, 0xb8, 0xcd, 0x41, 0x2a, 0xa7, 0xf7, 0x86, 0x95, 0x29, 0xf8, 0x37,
	0xb2, 0x43, 0x88, 0x80, 0xee, 0x01, 0x0f, 0xcc, 0xdc, 0xe8, 0xa3, 0x6d, 0x78, 0x8e, 0x8d, 0x73,
	0x8c, 0x5a, 0x0b, 0xc5, 0x33, 0x08, 0xc9, 0x1d, 0xae, 0xa2, 0x0b, 0x70, 0x69, 0xdf, 0x15, 0x6a,
	0x2f, 0xc5, 0x9a, 0x28, 0x08, 0x48, 0xa6, 0x0e, 0xff, 0xd8, 0x86, 0xe3, 0x8e, 0xf9, 0x57, 0x11,
	0xe7, 0xdb, 0x39, 0xa9, 0x4a, 0x0f, 0x8a, 0xd2, 0x6d, 0x17, 0xf9, 0x42, 0xcf, 0x28, 0xdb, 0x70,
	0x5d, 0xfb, 0x2f, 0x6a, 0x04, 0xb9, 0x4c, 0xaa, 0xda, 0x5a, 0x04, 0xe4, 0x90, 0x72, 0xb2, 0xbe,
	0x10, 0xd6, 0x29, 0xc2, 0x90, 0xdb, 0xf4, 0x45, 0x2e, 0x13, 0x9d, 0x33, 0x46, 0xd6, 0x1c, 0x52,
	0x50, 0x80, 0xfb, 0xc6, 0x55, 0xca, 0x63, 0xa5, 0x0f, 0x29, 0xfe, 0x85, 0xac, 0x10, 0xa4, 0x3e,
	0x7b, 0xbf, 0xba, 0x95, 0x3c, 0x39, 0xfc, 0xe0, 0x8c, 0x96, 0xeb, 0xa7, 0x23, 0x84, 0x29, 0xf7,
	0x56, 0xe9, 0xd6, 0x8b, 0x12, 0xba, 0x83, 0x8c, 0x78, 0x44, 0xd0, 0xa0, 0x76, 0x63, 0x1b, 0xf9,
	0x58, 0xef, 0x4e, 0xd3, 0x2d, 0xe5, 0xde, 0xcc, 0x8c, 0x27, 0x82, 0xae, 0xac, 0x22, 0x6a, 0xf4,
	0x1a, 0x00, 0x00, 0xff, 0xff, 0x7e, 0xa1, 0xcb, 0xf4, 0xcb, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ClientClient is the client API for Client service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ClientClient interface {
	// Get version of the server running
	Version(ctx context.Context, in *ApiVersion, opts ...grpc.CallOption) (*ApiVersion, error)
	// Checks if the server is running
	Upcheck(ctx context.Context, in *UpCheckResponse, opts ...grpc.CallOption) (*UpCheckResponse, error)
	// Used to store a transaction in the Chimera node
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
	// Retrieve a transaction from the Chimera node
	Receive(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (*ReceiveResponse, error)
	// Used to store a transaction locally
	StoreRaw(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*SendResponse, error)
	// Update the partyinfo with response from all the nodes connnected to the node
	UpdatePartyInfo(ctx context.Context, in *PartyInfo, opts ...grpc.CallOption) (*PartyInfoResponse, error)
	// Propogate payload to remote node
	Push(ctx context.Context, in *PushPayload, opts ...grpc.CallOption) (*PartyInfoResponse, error)
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteRequest, error)
	Resend(ctx context.Context, in *ResendRequest, opts ...grpc.CallOption) (*ResendResponse, error)
}

type clientClient struct {
	cc *grpc.ClientConn
}

func NewClientClient(cc *grpc.ClientConn) ClientClient {
	return &clientClient{cc}
}

func (c *clientClient) Version(ctx context.Context, in *ApiVersion, opts ...grpc.CallOption) (*ApiVersion, error) {
	out := new(ApiVersion)
	err := c.cc.Invoke(ctx, "/proto.Client/Version", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Upcheck(ctx context.Context, in *UpCheckResponse, opts ...grpc.CallOption) (*UpCheckResponse, error) {
	out := new(UpCheckResponse)
	err := c.cc.Invoke(ctx, "/proto.Client/Upcheck", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/proto.Client/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Receive(ctx context.Context, in *ReceiveRequest, opts ...grpc.CallOption) (*ReceiveResponse, error) {
	out := new(ReceiveResponse)
	err := c.cc.Invoke(ctx, "/proto.Client/Receive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) StoreRaw(ctx context.Context, in *StoreRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/proto.Client/StoreRaw", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) UpdatePartyInfo(ctx context.Context, in *PartyInfo, opts ...grpc.CallOption) (*PartyInfoResponse, error) {
	out := new(PartyInfoResponse)
	err := c.cc.Invoke(ctx, "/proto.Client/UpdatePartyInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Push(ctx context.Context, in *PushPayload, opts ...grpc.CallOption) (*PartyInfoResponse, error) {
	out := new(PartyInfoResponse)
	err := c.cc.Invoke(ctx, "/proto.Client/Push", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteRequest, error) {
	out := new(DeleteRequest)
	err := c.cc.Invoke(ctx, "/proto.Client/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *clientClient) Resend(ctx context.Context, in *ResendRequest, opts ...grpc.CallOption) (*ResendResponse, error) {
	out := new(ResendResponse)
	err := c.cc.Invoke(ctx, "/proto.Client/Resend", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClientServer is the server API for Client service.
type ClientServer interface {
	// Get version of the server running
	Version(context.Context, *ApiVersion) (*ApiVersion, error)
	// Checks if the server is running
	Upcheck(context.Context, *UpCheckResponse) (*UpCheckResponse, error)
	// Used to store a transaction in the Chimera node
	Send(context.Context, *SendRequest) (*SendResponse, error)
	// Retrieve a transaction from the Chimera node
	Receive(context.Context, *ReceiveRequest) (*ReceiveResponse, error)
	// Used to store a transaction locally
	StoreRaw(context.Context, *StoreRequest) (*SendResponse, error)
	// Update the partyinfo with response from all the nodes connnected to the node
	UpdatePartyInfo(context.Context, *PartyInfo) (*PartyInfoResponse, error)
	// Propogate payload to remote node
	Push(context.Context, *PushPayload) (*PartyInfoResponse, error)
	Delete(context.Context, *DeleteRequest) (*DeleteRequest, error)
	Resend(context.Context, *ResendRequest) (*ResendResponse, error)
}

// UnimplementedClientServer can be embedded to have forward compatible implementations.
type UnimplementedClientServer struct {
}

func (*UnimplementedClientServer) Version(ctx context.Context, req *ApiVersion) (*ApiVersion, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Version not implemented")
}
func (*UnimplementedClientServer) Upcheck(ctx context.Context, req *UpCheckResponse) (*UpCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upcheck not implemented")
}
func (*UnimplementedClientServer) Send(ctx context.Context, req *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (*UnimplementedClientServer) Receive(ctx context.Context, req *ReceiveRequest) (*ReceiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Receive not implemented")
}
func (*UnimplementedClientServer) StoreRaw(ctx context.Context, req *StoreRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StoreRaw not implemented")
}
func (*UnimplementedClientServer) UpdatePartyInfo(ctx context.Context, req *PartyInfo) (*PartyInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePartyInfo not implemented")
}
func (*UnimplementedClientServer) Push(ctx context.Context, req *PushPayload) (*PartyInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Push not implemented")
}
func (*UnimplementedClientServer) Delete(ctx context.Context, req *DeleteRequest) (*DeleteRequest, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (*UnimplementedClientServer) Resend(ctx context.Context, req *ResendRequest) (*ResendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Resend not implemented")
}

func RegisterClientServer(s *grpc.Server, srv ClientServer) {
	s.RegisterService(&_Client_serviceDesc, srv)
}

func _Client_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApiVersion)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Client/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).Version(ctx, req.(*ApiVersion))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_Upcheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpCheckResponse)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).Upcheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Client/Upcheck",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).Upcheck(ctx, req.(*UpCheckResponse))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Client/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_Receive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).Receive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Client/Receive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).Receive(ctx, req.(*ReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_StoreRaw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).StoreRaw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Client/StoreRaw",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).StoreRaw(ctx, req.(*StoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_UpdatePartyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PartyInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).UpdatePartyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Client/UpdatePartyInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).UpdatePartyInfo(ctx, req.(*PartyInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_Push_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PushPayload)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).Push(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Client/Push",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).Push(ctx, req.(*PushPayload))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Client/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Client_Resend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClientServer).Resend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.Client/Resend",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClientServer).Resend(ctx, req.(*ResendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Client_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Client",
	HandlerType: (*ClientServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Version",
			Handler:    _Client_Version_Handler,
		},
		{
			MethodName: "Upcheck",
			Handler:    _Client_Upcheck_Handler,
		},
		{
			MethodName: "Send",
			Handler:    _Client_Send_Handler,
		},
		{
			MethodName: "Receive",
			Handler:    _Client_Receive_Handler,
		},
		{
			MethodName: "StoreRaw",
			Handler:    _Client_StoreRaw_Handler,
		},
		{
			MethodName: "UpdatePartyInfo",
			Handler:    _Client_UpdatePartyInfo_Handler,
		},
		{
			MethodName: "Push",
			Handler:    _Client_Push_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Client_Delete_Handler,
		},
		{
			MethodName: "Resend",
			Handler:    _Client_Resend_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "grpc.proto",
}
