// Code generated by protoc-gen-go. DO NOT EDIT.
// source: messages.proto

package chimera

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The Apiversion on which the server is running
type ApiVersion struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApiVersion) Reset()         { *m = ApiVersion{} }
func (m *ApiVersion) String() string { return proto.CompactTextString(m) }
func (*ApiVersion) ProtoMessage()    {}
func (*ApiVersion) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{0}
}

func (m *ApiVersion) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApiVersion.Unmarshal(m, b)
}
func (m *ApiVersion) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApiVersion.Marshal(b, m, deterministic)
}
func (m *ApiVersion) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApiVersion.Merge(m, src)
}
func (m *ApiVersion) XXX_Size() int {
	return xxx_messageInfo_ApiVersion.Size(m)
}
func (m *ApiVersion) XXX_DiscardUnknown() {
	xxx_messageInfo_ApiVersion.DiscardUnknown(m)
}

var xxx_messageInfo_ApiVersion proto.InternalMessageInfo

func (m *ApiVersion) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

// The server response from an `upcheck` request
type UpCheckResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpCheckResponse) Reset()         { *m = UpCheckResponse{} }
func (m *UpCheckResponse) String() string { return proto.CompactTextString(m) }
func (*UpCheckResponse) ProtoMessage()    {}
func (*UpCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{1}
}

func (m *UpCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpCheckResponse.Unmarshal(m, b)
}
func (m *UpCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpCheckResponse.Marshal(b, m, deterministic)
}
func (m *UpCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpCheckResponse.Merge(m, src)
}
func (m *UpCheckResponse) XXX_Size() int {
	return xxx_messageInfo_UpCheckResponse.Size(m)
}
func (m *UpCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpCheckResponse proto.InternalMessageInfo

func (m *UpCheckResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// Store a transaction payload
type SendRequest struct {
	// The payload of the transaction to be sent
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// The key of the Sender
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// The keys of all the Receipients who are privy to the transaction
	To                   []string `protobuf:"bytes,3,rep,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendRequest) Reset()         { *m = SendRequest{} }
func (m *SendRequest) String() string { return proto.CompactTextString(m) }
func (*SendRequest) ProtoMessage()    {}
func (*SendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{2}
}

func (m *SendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendRequest.Unmarshal(m, b)
}
func (m *SendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendRequest.Marshal(b, m, deterministic)
}
func (m *SendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendRequest.Merge(m, src)
}
func (m *SendRequest) XXX_Size() int {
	return xxx_messageInfo_SendRequest.Size(m)
}
func (m *SendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendRequest proto.InternalMessageInfo

func (m *SendRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SendRequest) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *SendRequest) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

// Response from the server for the SendRequest
type SendResponse struct {
	// The transaction hash is returned
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendResponse) Reset()         { *m = SendResponse{} }
func (m *SendResponse) String() string { return proto.CompactTextString(m) }
func (*SendResponse) ProtoMessage()    {}
func (*SendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{3}
}

func (m *SendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendResponse.Unmarshal(m, b)
}
func (m *SendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendResponse.Marshal(b, m, deterministic)
}
func (m *SendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendResponse.Merge(m, src)
}
func (m *SendResponse) XXX_Size() int {
	return xxx_messageInfo_SendResponse.Size(m)
}
func (m *SendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendResponse proto.InternalMessageInfo

func (m *SendResponse) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

// Store a signed transaction payload
type SendSignedRequest struct {
	// The payload of the transaction to be sent
	Payload []byte `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	// The keys of all the Receipients who are privy to the transaction
	To                   []string `protobuf:"bytes,2,rep,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSignedRequest) Reset()         { *m = SendSignedRequest{} }
func (m *SendSignedRequest) String() string { return proto.CompactTextString(m) }
func (*SendSignedRequest) ProtoMessage()    {}
func (*SendSignedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{4}
}

func (m *SendSignedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSignedRequest.Unmarshal(m, b)
}
func (m *SendSignedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSignedRequest.Marshal(b, m, deterministic)
}
func (m *SendSignedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSignedRequest.Merge(m, src)
}
func (m *SendSignedRequest) XXX_Size() int {
	return xxx_messageInfo_SendSignedRequest.Size(m)
}
func (m *SendSignedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSignedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendSignedRequest proto.InternalMessageInfo

func (m *SendSignedRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *SendSignedRequest) GetTo() []string {
	if m != nil {
		return m.To
	}
	return nil
}

// Store a transaction payload locally and return a encrypted hash
type StoreRequest struct {
	// The payload of the transaction to be sent
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreRequest) Reset()         { *m = StoreRequest{} }
func (m *StoreRequest) String() string { return proto.CompactTextString(m) }
func (*StoreRequest) ProtoMessage()    {}
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{5}
}

func (m *StoreRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreRequest.Unmarshal(m, b)
}
func (m *StoreRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreRequest.Marshal(b, m, deterministic)
}
func (m *StoreRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreRequest.Merge(m, src)
}
func (m *StoreRequest) XXX_Size() int {
	return xxx_messageInfo_StoreRequest.Size(m)
}
func (m *StoreRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StoreRequest proto.InternalMessageInfo

func (m *StoreRequest) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Retrieve a transaction payload
type ReceiveRequest struct {
	// The transaction hash to be queried
	Key []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// The Senders key
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveRequest) Reset()         { *m = ReceiveRequest{} }
func (m *ReceiveRequest) String() string { return proto.CompactTextString(m) }
func (*ReceiveRequest) ProtoMessage()    {}
func (*ReceiveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{6}
}

func (m *ReceiveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveRequest.Unmarshal(m, b)
}
func (m *ReceiveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveRequest.Marshal(b, m, deterministic)
}
func (m *ReceiveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveRequest.Merge(m, src)
}
func (m *ReceiveRequest) XXX_Size() int {
	return xxx_messageInfo_ReceiveRequest.Size(m)
}
func (m *ReceiveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveRequest proto.InternalMessageInfo

func (m *ReceiveRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *ReceiveRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

// Response for ReceiveRequest -> contains the transaction payload
type ReceiveResponse struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReceiveResponse) Reset()         { *m = ReceiveResponse{} }
func (m *ReceiveResponse) String() string { return proto.CompactTextString(m) }
func (*ReceiveResponse) ProtoMessage()    {}
func (*ReceiveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{7}
}

func (m *ReceiveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReceiveResponse.Unmarshal(m, b)
}
func (m *ReceiveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReceiveResponse.Marshal(b, m, deterministic)
}
func (m *ReceiveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReceiveResponse.Merge(m, src)
}
func (m *ReceiveResponse) XXX_Size() int {
	return xxx_messageInfo_ReceiveResponse.Size(m)
}
func (m *ReceiveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReceiveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReceiveResponse proto.InternalMessageInfo

func (m *ReceiveResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Node information
type PartyInfo struct {
	// the URL identifying this node
	Url string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// public key of the respective URL
	Recipients map[string][]byte `protobuf:"bytes,2,rep,name=recipients,proto3" json:"recipients,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// All the URLs opf the connected nodes
	Parties              map[string]bool `protobuf:"bytes,3,rep,name=parties,proto3" json:"parties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"varint,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *PartyInfo) Reset()         { *m = PartyInfo{} }
func (m *PartyInfo) String() string { return proto.CompactTextString(m) }
func (*PartyInfo) ProtoMessage()    {}
func (*PartyInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{8}
}

func (m *PartyInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyInfo.Unmarshal(m, b)
}
func (m *PartyInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyInfo.Marshal(b, m, deterministic)
}
func (m *PartyInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyInfo.Merge(m, src)
}
func (m *PartyInfo) XXX_Size() int {
	return xxx_messageInfo_PartyInfo.Size(m)
}
func (m *PartyInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyInfo.DiscardUnknown(m)
}

var xxx_messageInfo_PartyInfo proto.InternalMessageInfo

func (m *PartyInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *PartyInfo) GetRecipients() map[string][]byte {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *PartyInfo) GetParties() map[string]bool {
	if m != nil {
		return m.Parties
	}
	return nil
}

// Payload consisting of the partyinfo of the connected party
type PartyInfoResponse struct {
	Payload              []byte   `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PartyInfoResponse) Reset()         { *m = PartyInfoResponse{} }
func (m *PartyInfoResponse) String() string { return proto.CompactTextString(m) }
func (*PartyInfoResponse) ProtoMessage()    {}
func (*PartyInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{9}
}

func (m *PartyInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PartyInfoResponse.Unmarshal(m, b)
}
func (m *PartyInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PartyInfoResponse.Marshal(b, m, deterministic)
}
func (m *PartyInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PartyInfoResponse.Merge(m, src)
}
func (m *PartyInfoResponse) XXX_Size() int {
	return xxx_messageInfo_PartyInfoResponse.Size(m)
}
func (m *PartyInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PartyInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PartyInfoResponse proto.InternalMessageInfo

func (m *PartyInfoResponse) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

// The Encrypted payload used to propogate the new transaction payload to other Chimera nodes
type EncryptedPayload struct {
	Sender               []byte   `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	CipherText           []byte   `protobuf:"bytes,2,opt,name=cipherText,proto3" json:"cipherText,omitempty"`
	Nonce                []byte   `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ReciepientBoxes      [][]byte `protobuf:"bytes,4,rep,name=reciepientBoxes,proto3" json:"reciepientBoxes,omitempty"`
	ReciepientNonce      []byte   `protobuf:"bytes,5,opt,name=reciepientNonce,proto3" json:"reciepientNonce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EncryptedPayload) Reset()         { *m = EncryptedPayload{} }
func (m *EncryptedPayload) String() string { return proto.CompactTextString(m) }
func (*EncryptedPayload) ProtoMessage()    {}
func (*EncryptedPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{10}
}

func (m *EncryptedPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EncryptedPayload.Unmarshal(m, b)
}
func (m *EncryptedPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EncryptedPayload.Marshal(b, m, deterministic)
}
func (m *EncryptedPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EncryptedPayload.Merge(m, src)
}
func (m *EncryptedPayload) XXX_Size() int {
	return xxx_messageInfo_EncryptedPayload.Size(m)
}
func (m *EncryptedPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_EncryptedPayload.DiscardUnknown(m)
}

var xxx_messageInfo_EncryptedPayload proto.InternalMessageInfo

func (m *EncryptedPayload) GetSender() []byte {
	if m != nil {
		return m.Sender
	}
	return nil
}

func (m *EncryptedPayload) GetCipherText() []byte {
	if m != nil {
		return m.CipherText
	}
	return nil
}

func (m *EncryptedPayload) GetNonce() []byte {
	if m != nil {
		return m.Nonce
	}
	return nil
}

func (m *EncryptedPayload) GetReciepientBoxes() [][]byte {
	if m != nil {
		return m.ReciepientBoxes
	}
	return nil
}

func (m *EncryptedPayload) GetReciepientNonce() []byte {
	if m != nil {
		return m.ReciepientNonce
	}
	return nil
}

// The message type to sent over to other Chimera nodes.
type PushPayload struct {
	Ep *EncryptedPayload `protobuf:"bytes,1,opt,name=ep,proto3" json:"ep,omitempty"`
	// Encoded transaction information
	Encoded              []byte   `protobuf:"bytes,2,opt,name=encoded,proto3" json:"encoded,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PushPayload) Reset()         { *m = PushPayload{} }
func (m *PushPayload) String() string { return proto.CompactTextString(m) }
func (*PushPayload) ProtoMessage()    {}
func (*PushPayload) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{11}
}

func (m *PushPayload) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PushPayload.Unmarshal(m, b)
}
func (m *PushPayload) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PushPayload.Marshal(b, m, deterministic)
}
func (m *PushPayload) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PushPayload.Merge(m, src)
}
func (m *PushPayload) XXX_Size() int {
	return xxx_messageInfo_PushPayload.Size(m)
}
func (m *PushPayload) XXX_DiscardUnknown() {
	xxx_messageInfo_PushPayload.DiscardUnknown(m)
}

var xxx_messageInfo_PushPayload proto.InternalMessageInfo

func (m *PushPayload) GetEp() *EncryptedPayload {
	if m != nil {
		return m.Ep
	}
	return nil
}

func (m *PushPayload) GetEncoded() []byte {
	if m != nil {
		return m.Encoded
	}
	return nil
}

type DeleteRequest struct {
	Key                  []byte   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRequest) Reset()         { *m = DeleteRequest{} }
func (m *DeleteRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRequest) ProtoMessage()    {}
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{12}
}

func (m *DeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRequest.Unmarshal(m, b)
}
func (m *DeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRequest.Merge(m, src)
}
func (m *DeleteRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRequest.Size(m)
}
func (m *DeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRequest proto.InternalMessageInfo

func (m *DeleteRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

// ResendRequest is used to resend previous transactions.
// There are two types of supported request.
// 1. All transactions associated with a node, in which case the Key field should be omitted.
// 2. A specific transaction with the given key value.
type ResendRequest struct {
	// Type is the resend request type. It should be either "all" or "individual" depending on if
	// you want to request an individual transaction, or all transactions associated with a node.
	Type                 string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	PublicKey            []byte   `protobuf:"bytes,2,opt,name=PublicKey,proto3" json:"PublicKey,omitempty"`
	Key                  []byte   `protobuf:"bytes,3,opt,name=Key,proto3" json:"Key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendRequest) Reset()         { *m = ResendRequest{} }
func (m *ResendRequest) String() string { return proto.CompactTextString(m) }
func (*ResendRequest) ProtoMessage()    {}
func (*ResendRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{13}
}

func (m *ResendRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendRequest.Unmarshal(m, b)
}
func (m *ResendRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendRequest.Marshal(b, m, deterministic)
}
func (m *ResendRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendRequest.Merge(m, src)
}
func (m *ResendRequest) XXX_Size() int {
	return xxx_messageInfo_ResendRequest.Size(m)
}
func (m *ResendRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ResendRequest proto.InternalMessageInfo

func (m *ResendRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *ResendRequest) GetPublicKey() []byte {
	if m != nil {
		return m.PublicKey
	}
	return nil
}

func (m *ResendRequest) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

type ResendResponse struct {
	Encoded              []byte   `protobuf:"bytes,1,opt,name=encoded,proto3" json:"encoded,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResendResponse) Reset()         { *m = ResendResponse{} }
func (m *ResendResponse) String() string { return proto.CompactTextString(m) }
func (*ResendResponse) ProtoMessage()    {}
func (*ResendResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4dc296cbfe5ffcd5, []int{14}
}

func (m *ResendResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResendResponse.Unmarshal(m, b)
}
func (m *ResendResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResendResponse.Marshal(b, m, deterministic)
}
func (m *ResendResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResendResponse.Merge(m, src)
}
func (m *ResendResponse) XXX_Size() int {
	return xxx_messageInfo_ResendResponse.Size(m)
}
func (m *ResendResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ResendResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ResendResponse proto.InternalMessageInfo

func (m *ResendResponse) GetEncoded() []byte {
	if m != nil {
		return m.Encoded
	}
	return nil
}

func init() {
	proto.RegisterType((*ApiVersion)(nil), "proto.ApiVersion")
	proto.RegisterType((*UpCheckResponse)(nil), "proto.UpCheckResponse")
	proto.RegisterType((*SendRequest)(nil), "proto.SendRequest")
	proto.RegisterType((*SendResponse)(nil), "proto.SendResponse")
	proto.RegisterType((*SendSignedRequest)(nil), "proto.SendSignedRequest")
	proto.RegisterType((*StoreRequest)(nil), "proto.StoreRequest")
	proto.RegisterType((*ReceiveRequest)(nil), "proto.ReceiveRequest")
	proto.RegisterType((*ReceiveResponse)(nil), "proto.ReceiveResponse")
	proto.RegisterType((*PartyInfo)(nil), "proto.PartyInfo")
	proto.RegisterMapType((map[string]bool)(nil), "proto.PartyInfo.PartiesEntry")
	proto.RegisterMapType((map[string][]byte)(nil), "proto.PartyInfo.RecipientsEntry")
	proto.RegisterType((*PartyInfoResponse)(nil), "proto.PartyInfoResponse")
	proto.RegisterType((*EncryptedPayload)(nil), "proto.EncryptedPayload")
	proto.RegisterType((*PushPayload)(nil), "proto.PushPayload")
	proto.RegisterType((*DeleteRequest)(nil), "proto.DeleteRequest")
	proto.RegisterType((*ResendRequest)(nil), "proto.ResendRequest")
	proto.RegisterType((*ResendResponse)(nil), "proto.ResendResponse")
}

func init() { proto.RegisterFile("messages.proto", fileDescriptor_4dc296cbfe5ffcd5) }

var fileDescriptor_4dc296cbfe5ffcd5 = []byte{
	// 566 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x55, 0xb2, 0xfd, 0x60, 0x67, 0xb7, 0x5f, 0x16, 0x82, 0xa8, 0x02, 0xb4, 0xe4, 0x00, 0x2b,
	0x2a, 0x72, 0xd8, 0x1e, 0x40, 0x95, 0x2a, 0xd1, 0x96, 0x1e, 0x50, 0x25, 0x14, 0x79, 0x0b, 0x07,
	0x6e, 0x69, 0x32, 0xed, 0x5a, 0x9b, 0xda, 0xc6, 0xf6, 0x56, 0xcd, 0xef, 0xe0, 0x5f, 0x70, 0xe6,
	0x07, 0x22, 0x3b, 0x4e, 0x9a, 0xb6, 0xaa, 0xda, 0xd3, 0xce, 0x38, 0xef, 0xbd, 0x79, 0xf3, 0xbc,
	0x86, 0xf5, 0x4b, 0xd4, 0x3a, 0xbb, 0x40, 0x9d, 0x48, 0x25, 0x8c, 0x20, 0xcb, 0xee, 0x27, 0x7e,
	0x07, 0x70, 0x20, 0xd9, 0x4f, 0x54, 0x9a, 0x09, 0x4e, 0x22, 0x58, 0xbd, 0xaa, 0xcb, 0x28, 0x18,
	0x05, 0xe3, 0x3e, 0x6d, 0xda, 0x78, 0x07, 0x36, 0x7e, 0xc8, 0xa3, 0x19, 0xe6, 0x73, 0x8a, 0x5a,
	0x0a, 0xae, 0xd1, 0x82, 0xbd, 0x66, 0x03, 0xf6, 0x6d, 0x7c, 0x02, 0x83, 0x29, 0xf2, 0x82, 0xe2,
	0xef, 0x05, 0x6a, 0x63, 0x81, 0x32, 0xab, 0x4a, 0x91, 0x15, 0x0e, 0x38, 0xa4, 0x4d, 0x4b, 0x08,
	0x2c, 0x9d, 0x2b, 0x71, 0x19, 0x85, 0x8e, 0xef, 0x6a, 0xb2, 0x0e, 0xa1, 0x11, 0x51, 0x6f, 0xd4,
	0x1b, 0xf7, 0x69, 0x68, 0x44, 0x3c, 0x82, 0x61, 0x2d, 0xe6, 0xc7, 0x6e, 0x42, 0x6f, 0x8e, 0x95,
	0x57, 0xb2, 0x65, 0xbc, 0x0f, 0x5b, 0x16, 0x31, 0x65, 0x17, 0x1c, 0x9f, 0x30, 0xb4, 0x1e, 0x10,
	0xb6, 0x03, 0xc6, 0x30, 0x9c, 0x1a, 0xa1, 0xf0, 0x51, 0x66, 0x3c, 0x81, 0x75, 0x8a, 0x39, 0xb2,
	0xab, 0x16, 0x7b, 0xcf, 0x4c, 0xab, 0x1e, 0x78, 0xf5, 0x1d, 0xd8, 0x68, 0x39, 0x37, 0xc1, 0x3d,
	0x30, 0xe0, 0x4f, 0x08, 0xfd, 0x34, 0x53, 0xa6, 0xfa, 0xc6, 0xcf, 0x85, 0x15, 0x5f, 0xa8, 0xd2,
	0x87, 0x6b, 0x4b, 0xf2, 0x05, 0x40, 0x61, 0xce, 0x24, 0x43, 0x6e, 0xb4, 0x5b, 0x61, 0x30, 0x19,
	0xd5, 0x17, 0x9a, 0xb4, 0xbc, 0x84, 0xb6, 0x90, 0x63, 0x6e, 0x54, 0x45, 0x3b, 0x1c, 0xf2, 0xc9,
	0xce, 0x56, 0x86, 0xa1, 0x76, 0x11, 0x0f, 0x26, 0xaf, 0xef, 0xd1, 0xd3, 0xfa, 0x7b, 0xcd, 0x6d,
	0xd0, 0xdb, 0xfb, 0x6e, 0x8f, 0xae, 0x6e, 0x77, 0xf9, 0x7e, 0xbd, 0xfc, 0x73, 0x58, 0xbe, 0xca,
	0xca, 0x05, 0xba, 0xfd, 0x87, 0xb4, 0x6e, 0xf6, 0xc2, 0xcf, 0xc1, 0xf6, 0x1e, 0x0c, 0xbb, 0xba,
	0x8f, 0x71, 0x9f, 0x75, 0xb8, 0xf1, 0x47, 0xd8, 0x6a, 0xdd, 0x3d, 0x21, 0xc4, 0x7f, 0x01, 0x6c,
	0x1e, 0xf3, 0x5c, 0x55, 0xd2, 0x60, 0x91, 0xfa, 0x4b, 0x7f, 0x01, 0x2b, 0x1a, 0x79, 0x81, 0xca,
	0xa3, 0x7d, 0x47, 0xde, 0x00, 0xe4, 0x4c, 0xce, 0x50, 0x9d, 0xe2, 0xb5, 0xf1, 0xb6, 0x3b, 0x27,
	0xd6, 0x15, 0x17, 0x3c, 0xc7, 0xa8, 0x57, 0x6f, 0xe4, 0x1a, 0x32, 0x86, 0x0d, 0x9b, 0x29, 0xba,
	0x34, 0x0e, 0xc5, 0x35, 0xea, 0x68, 0x69, 0xd4, 0x1b, 0x0f, 0xe9, 0xdd, 0xe3, 0xdb, 0xc8, 0xef,
	0x4e, 0x69, 0xd9, 0x29, 0xdd, 0x3d, 0x8e, 0x53, 0x18, 0xa4, 0x0b, 0x3d, 0x6b, 0x0c, 0xbf, 0x87,
	0x10, 0xa5, 0x33, 0x3b, 0x98, 0xbc, 0xf4, 0x77, 0x74, 0x77, 0x2b, 0x1a, 0xa2, 0xb4, 0x41, 0x20,
	0xcf, 0x45, 0x81, 0x85, 0xb7, 0xdf, 0xb4, 0xf1, 0x5b, 0x58, 0xfb, 0x8a, 0x25, 0x9a, 0x87, 0xff,
	0xad, 0xf1, 0x14, 0xd6, 0x28, 0xea, 0xce, 0x5b, 0x25, 0xb0, 0x74, 0x5a, 0xc9, 0xe6, 0x45, 0xbb,
	0x9a, 0xbc, 0x82, 0x7e, 0xba, 0x38, 0x2b, 0x59, 0x7e, 0x82, 0x95, 0x9f, 0x71, 0x73, 0x60, 0x45,
	0xed, 0x79, 0x9d, 0x8f, 0x2d, 0xe3, 0x0f, 0xf6, 0x99, 0xe8, 0xee, 0x9b, 0xed, 0x78, 0x0c, 0x6e,
	0x79, 0x3c, 0xdc, 0x05, 0xc2, 0x44, 0x72, 0x56, 0xce, 0x93, 0x7c, 0xc6, 0x2e, 0x51, 0x65, 0x49,
	0x26, 0x59, 0x1a, 0xfc, 0x5a, 0xf5, 0xed, 0xdf, 0x70, 0xeb, 0xb0, 0x9c, 0x33, 0x91, 0x1c, 0xf9,
	0xcf, 0x07, 0x92, 0x9d, 0xad, 0xb8, 0x38, 0x76, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x50, 0x8e,
	0xa9, 0x32, 0xd4, 0x04, 0x00, 0x00,
}
